name: prover

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Cache OPAM dependencies
        uses: actions/cache@v3
        with:
          path: ~/.opam
          key: opam-${{ runner.os }}-${{ hashFiles('**/*.opam') }}
          restore-keys: |
            opam-${{ runner.os }}-

      - name: Build Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: false
          tags: prover-ocaml-image
          load: true

      - name: Run tests
        run: docker run --rm proover-ocaml-image dune runtest
  
      - name: Run zanuda linter
        run: docker run --rm proover-ocaml-image zanuda

      - name: Debug on failure
        if: failure()
        run: |
          docker run --rm prover-ocaml-image opam list
          docker run --rm prover-ocaml-image opam config report